import streamlit as st
from minidalle import MinDalle
from PIL import Image
import io
import torch

st.set_page_config(page_title="Ludy 1.1 – Image Generator", layout="wide")

st.title("🖼️ Ludy 1.1 – Lightweight AI Image Generator")
st.markdown("""
This is **Ludy 1.1** – a simple, fast image generator using Mini-DALL-E (no heavy downloads, works on CPU).  
Type any prompt and generate!

**Examples:**
- "cartoon cactus sitting on toilet with microphone to crowd, funny"
- "red car at sunset with mountains, anime style"
- "cute cat astronaut eating pizza in space"

First generation may take 10–30 seconds while model loads.
""")

# Load Mini-DALL-E (small model, downloads ~300 MB first time)
@st.cache_resource
def load_model():
    with st.spinner("Loading Ludy 1.1 model (first time only, ~30 sec)..."):
        model = MinDalle(is_mega=False, models_root='./models')  # is_mega=False = small & fast
    return model

model = load_model()

prompt = st.text_input("Enter your prompt:", "cartoonish cactus sitting on the toilet with a microphone reaching out to a crowd, funny style")

if st.button("Generate Image"):
    if prompt.strip():
        with st.spinner("Generating image... (10–30 seconds)"):
            try:
                # Generate with Mini-DALL-E
                image = model.generate_image(
                    text=prompt,
                    seed=-1,  # random
                    grid_size=2,  # 2x2 grid = 4 variations
                    is_seamless=False,
                    temperature=1.0
                )

                # Display
                st.image(image, caption=f"Generated by Ludy 1.1: {prompt}")

                # Download
                buf = io.BytesIO()
                image.save(buf, format="PNG")
                byte_im = buf.getvalue()
                st.download_button(
                    label="Download Image",
                    data=byte_im,
                    file_name="ludy_image.png",
                    mime="image/png"
                )

            except Exception as e:
                st.error(f"Oops! Error: {str(e)}\nTry a shorter prompt or refresh.")
    else:
        st.warning("Please enter a prompt!")

st.markdown("---")
st.caption("Ludy 1.1 • Powered by SmartBot Ludy 1.1 • Running on SmartBot Data Center • Created by BotDevelopmentAI")
